import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"
import Providers from "./Providers"
import LoginButton from "../components/LoginButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
        <header className="bg-blue-500 text-white p-4">
          <nav className="flex gap-8 max-w-4xl mx-auto">
            <Link href="/">ホーム</Link>
            <Link href="/about">About</Link>
            <LoginButton />
          </nav>
        </header>
        {children}
        </Providers>
        </body>
        <footer className="bg-gray-800 text-white text-center p-4 mt-auto">
        <p>© 2025 My Portfolio</p>
        </footer>
    </html>
  );
}
